services:
  - type: web
    name: armvet
    env: static
    buildCommand: bash build.sh
    staticPublishPath: dist
    envVars:
      - key: SITE_DOMAIN
        value: armvet-llc.com
      - key: VITE_API_URL
        sync: false
